apiVersion: v1
kind: Service
metadata:
  name: vinyl-spins-ui
  namespace: vinyl-spins
spec:
  selector:
    app: vinyl-spins-ui
  ports:
    - name: http
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vinyl-spins-ui
  namespace: vinyl-spins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vinyl-spins-ui
  template:
    metadata:
      labels:
        app: vinyl-spins-ui
    spec:
      containers:
        - name: ui
          # Build/push this image from `frontend/Dockerfile.prod`.
          image: stmcallisterbridge4/vst-ui:926f00a5ddaf0c679290a38510cb53a23e437b06
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http

